services:
  dataapps:
    build: .
    container_name: ${CONTAINER_NAME:-dataapps-template}
    ports:
      - "${HOST_PORT:-8000}:8000"
    environment:
      - PORT=8000
      - CORS_ORIGINS=*
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

# Optional: Add database service when needed
# services:
#   dataapps:
#     # ... existing config ...
#     depends_on:
#       - postgres
#     environment:
#       - DATABASE_URL=postgresql://user:password@postgres:5432/dataapps
#   
#   postgres:
#     image: postgres:15-alpine
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: dataapps
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
# 
# volumes:
#   postgres_data: