services:
  backend:
    build:
      context: .
      dockerfile: server/server.Dockerfile
    ports:
      - "2022:2022"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@localhost:5432/postgres}
    container_name: app-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2022/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: client/client.Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://app-backend:2022 # Reference the backend by container name
