services:
  apiserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: prod
    ports:
      - "8001:8001"
    privileged: true
    environment:
      - PYTHONPATH=/app
      - BUILDER_TOKEN=${BUILDER_TOKEN:-} # Optional auth token, empty string disables auth
    volumes:
      - ${DOCKER_SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 3s
      timeout: 30s
      retries: 3
      start_period: 3s
