id: avoid-ui-element-in-config
language: python
message: Do not assign NiceGUI UI elements into config/dict; store values (e.g., .value) not elements.
severity: error
rule:
  any:
    - pattern: "$CONF[$KEY] = ui.input($ARGS)"
    - pattern: "$CONF[$KEY] = ui.textarea($ARGS)"
    - pattern: "$CONF[$KEY] = ui.number($ARGS)"
    - pattern: "$CONF[$KEY] = ui.select($ARGS)"
