name: Build and Test

on:
  push:
    branches:
      - mock/sdk
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build TypeSpec Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./agent
          file: ./agent/Dockerfile.typespec
          tags: botbuild/tsp_compiler
          push: false
          load: true
          # Use gha cache backend
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Application Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./agent
          file: ./agent/Dockerfile.application
          tags: botbuild/app_schema
          push: false
          load: true
          # Use gha cache backend
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pull PostgreSQL image
        run: docker pull postgres:17.0-alpine

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r agent/requirements.txt

      - name: Run tests
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        run: |
          # Give the current user access to docker socket
          sudo chmod 666 /var/run/docker.sock
          PYTHONPATH=$PYTHONPATH:./agent/ uv run pytest -vs agent/tests

      - name: Clean up
        if: always()
        run: |
          docker image prune -f
