name: Rust

on:
  push:
    branches:
      - main
  pull_request:

env:
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  rust-checks:
    name: Check and Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            dabgent/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo check
        working-directory: ./dabgent
        run: cargo check --workspace --exclude dabgent_cli  # TEMP: Exclude dabgent_cli due to compilation issues

      - name: Run cargo clippy
        working-directory: ./dabgent
        run: cargo clippy --workspace --exclude dabgent_cli -- -W warnings  # TEMP: Exclude dabgent_cli
        continue-on-error: true

  rust-tests:
    name: Rust Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            dabgent/target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Run unit tests
        working-directory: ./dabgent
        run: cargo test --lib --workspace --exclude dabgent_cli  # TEMP: Exclude dabgent_cli
        continue-on-error: true

      - name: Run integration tests (excluding e2e)
        working-directory: ./dabgent
        run: cargo test --workspace --exclude dabgent_cli --test '*' -- --skip e2e_generation  # TEMP: Exclude dabgent_cli
        continue-on-error: true
