name: Rust Main Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "agent/**"
  pull_request:
    paths-ignore:
      - "agent/**"

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            dabgent/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo check
        working-directory: ./dabgent
        run: cargo check

      - name: Run cargo clippy
        working-directory: ./dabgent
        run: cargo clippy -- -W warnings
        continue-on-error: true

  rust-tests:
    name: Rust Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            dabgent/target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Run unit tests
        working-directory: ./dabgent
        run: cargo test --lib --all
        continue-on-error: true

      - name: Run integration tests (excluding e2e)
        working-directory: ./dabgent
        run: cargo test --all --test '*' -- --skip e2e_generation
        continue-on-error: true
